apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdbobsidian
  namespace: couchdb
  labels:
    app: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - name: couchdb
        image: couchdb
        ports:
        - containerPort: 5984
        volumeMounts:
        - mountPath: /opt/couchdb/data
          name: couchdb-data
        - mountPath: /opt/couchdb/data/docker.ini
          subPath: docker.ini
          name: couchdb-config
        env:
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: username
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: password
        command: ["/bin/sh"]
        args:
        - "-c"
        - |
          cp /opt/couchdb/data/docker.ini /opt/couchdb/etc/local.d/ && exec /opt/couchdb/bin/couchdb
      volumes:
      - name: couchdb-data
        persistentVolumeClaim:
          claimName: couchdb-pvc
      - name: couchdb-config
        configMap:
          name: couchdb-config
---
apiVersion: v1
kind: Service
metadata:
  name: couchdb-service
  namespace: couchdb
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.23.35
  ports:
    - port: 5984
      targetPort: 5984
  selector:
    app: couchdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-config
  namespace: couchdb
data:
  docker.ini: |
    [couchdb]
    single_node=true
    max_document_size = 50000000

    [chttpd]
    require_valid_user = true
    max_http_request_size = 4294967296
    enable_cors = true

    [chttpd_auth]
    require_valid_user = true
    authentication_redirect = /_utils/session.html

    [httpd]
    WWW-Authenticate = Basic realm="couchdb"
    bind_address = 0.0.0.0

    [cors]
    origins = app://obsidian.md, capacitor://localhost, http://localhost
    credentials = true
    headers = accept, authorization, content-type, origin, referer
    methods = GET,PUT,POST,HEAD,DELETE
    max_age = 3600
---
apiVersion: v1
kind: Secret
metadata:
  name: couchdb-secret
  namespace: couchdb
type: Opaque
data:
  username: YWRtaW4=  # base64 for 'admin'
  password: cGFzc3dvcmQ=  # base64 for 'password'
