apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdbobsidian
  namespace: couchdb
  labels:
    app: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      initContainers:
      - name: init-config
        image: busybox
        command: ['sh', '-c', 'echo "Starting Init Container"; ls -l /config; ls -l /opt/couchdb/etc; cat /config/custom.ini >> /opt/couchdb/etc/local.ini']
        volumeMounts:
        - mountPath: /config/custom.ini
          subPath: custom.ini
          name: couchdb-config
        - mountPath: /opt/couchdb/etc/local.ini
          name: couchdb-local-ini
      containers:
      - name: couchdb
        image: couchdb
        ports:
        - containerPort: 5984
        volumeMounts:
        - mountPath: /opt/couchdb/data
          name: couchdb-data
        - mountPath: /opt/couchdb/etc/local.ini
          name: couchdb-local-ini
        env:
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: username
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: password
      volumes:
      - name: couchdb-data
        persistentVolumeClaim:
          claimName: couchdb-pvc
      - name: couchdb-config
        configMap:
          name: couchdb-config
      - name: couchdb-local-ini
        emptyDir: {}
