apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdbobsidian
  namespace: couchdb
  labels:
    app: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      initContainers:
      - name: init-config
        image: busybox
        command: ['sh', '-c', 'cat /config/custom.ini >> /opt/couchdb/etc/local.ini']
        volumeMounts:
        - mountPath: /config/custom.ini
          subPath: custom.ini
          name: couchdb-config
        - mountPath: /opt/couchdb/etc/local.ini
          subPath: local.ini  # This ensures local.ini is mounted as a file
          name: couchdb-local-ini
      containers:
      - name: couchdb
        image: couchdb
        ports:
        - containerPort: 5984
        volumeMounts:
        - mountPath: /opt/couchdb/data
          name: couchdb-data
        - mountPath: /opt/couchdb/etc/local.ini
          subPath: local.ini  # Again, ensure local.ini is a file
          name: couchdb-local-ini
        env:
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: couchd
